### ISSUE TITLE
when I try to compile I get this error (im on linux btw)

### ISSUE THREAD

**Issue by Gegenter** [quentinguidee/Omega#14]
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
Opening DFU capable USB device...
ID 0483:a291
Run-time device DFU version 0100
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0100
Device returned transfer size 2048
DfuSe interface name: "Flash"
Downloading to address = 0x08000000, size = 782156
dfu-util: Last page at 0x080bef4b is not writeable
make: *** [scripts/targets.device.mak:43: epsilon_flash] Error 74
rm build/device/epsilon.bin

**Comment by Gegenter** [comment]
Could this be because Im on version 12.0.0? How could I downgrade and/or when is the new version coming out?

**Comment by Gegenter** [comment]
okay, It wont even work on version 11.2.0 could someone help me out here?

**Comment by RedGl0w** [comment]
Can you try to list all the devices with the command : `dfu-util -l` ?

**Comment by Gegenter** [comment]
when i type in the command this is what i get
[gegenter@gegenter-pc ~]$ dfu-util -l
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

**Comment by RedGl0w** [comment]
Normally with the calculator connected (sorry I've forgotten) and with sudo, it tells you if it is recognized  (`Found DFU: [0483:a291] ver=0100, devnum=7, cfg=1, intf=0, path="1-2", alt=0, name="@Flash/0x08000000/04*016Kg,01*064Kg,07*128Kg", serial="GYAYAAVRODAxOTA5"`)

**Comment by Gegenter** [comment]
okay yes it is connected:
Found DFU: [0483:a291] ver=0100, devnum=56, cfg=1, intf=0, path="1-12", alt=0, name="@Flash/0x08000000/04*016Kg/0x90000000/64*064Kg,64*064Kg", serial="NwBRABdRODIwMzM4"

**Comment by RedGl0w** [comment]
which model of numworks have you got ? N0100 or N0110 ?

**Comment by Gegenter** [comment]
N0110

**Comment by RedGl0w** [comment]
Try `make MODEL=N0110` and `make MODEL=N0110 epsilon_flash`
I don't know quentinguidee has updated this repository for the new models...

**Comment by Gegenter** [comment]
I am still getting the error, so it is probably because of the new models?

**Comment by MixedMatched** [comment]
This repo hasn't been updated for the N0110, yet. The next update is probably going to be primarily focused on merging most of the 12 branch in,

**Comment by Gegenter** [comment]
oh okay thank you though,I will be waiting then haha.

**Comment by quentinguidee** [comment]
@Gegenter Hello! I just updated Omega with Epsilon 12.0.0! Can you try if it's working now on n0110?

Thank you very much!!

**Comment by Gegenter** [comment]
okay i just tested it,sorry it took so long, so yes it is indeed working!

**Comment by RedGl0w** [comment]
And I've got a question
When you enter in exam mode and you power off your calculator, does it stay in exam mode ?

**Comment by Gegenter** [comment]
Yes it stays in exam mode

**Comment by RedGl0w** [comment]
Ok thank you !

**Comment by RedGl0w** [comment]
And does the LED continue blinking ?

**Comment by Gegenter** [comment]
No it stops blinking,it disappears completely. So i guess that is a problem that needs to be worked on.

**Comment by RedGl0w** [comment]
Ok I'll make an issue about that
