### ISSUE TITLE
The name should be something else.

### ISSUE THREAD

**Issue by MixedMatched** [quentinguidee/Omega#6]
The name "LavaOS" isn't bad, but it isn't really good. It doesn't relate to the function of the calculator/OS or the base of the project, Epsilon. I think something like Omega, because of its relation to Epsilon in set theory, or Lambda, because both Epsilon and Lambda can represent the empty string in CS, would make more sense.

**Comment by quentinguidee** [comment]
Good idea! Do you think that names like Omega can be used here without rights issues or anything?

**Comment by MixedMatched** [comment]
Yeah. It's a Greek letter, so no one can trademark it.

**Comment by quentinguidee** [comment]
Oh, perfect! I will change the name in a few days :)

**Comment by quentinguidee** [comment]
Hi! The new project name is now Omega!
